/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package EQueen.View;

import javax.swing.ButtonGroup;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author ADMIN
 */
public class TroChoiMoiView extends javax.swing.JFrame {

    /**
     * Creates new form TrangChuView
     */
    public TroChoiMoiView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        pnMenu = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbTroChoiMoi = new javax.swing.JLabel();
        lbNhatKy = new javax.swing.JLabel();
        lbX = new javax.swing.JLabel();
        lbTrangChu = new javax.swing.JLabel();
        lbTroGiup = new javax.swing.JLabel();
        lbGioiThieu = new javax.swing.JLabel();
        lbThoat = new javax.swing.JLabel();
        lbIcon = new javax.swing.JLabel();
        lbMenu = new javax.swing.JLabel();
        txtNumber = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rbtQueen = new javax.swing.JRadioButton();
        rbtKnight = new javax.swing.JRadioButton();
        lbChoiNgay = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trò chơi mới");
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMinimumSize(new java.awt.Dimension(1200, 700));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnMenu.setBackground(new java.awt.Color(255, 255, 255));
        pnMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        pnMenu.setMinimumSize(new java.awt.Dimension(250, 100));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel2.setMinimumSize(new java.awt.Dimension(249, 100));

        lbTroChoiMoi.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbTroChoiMoi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTroChoiMoi.setText(" Trò chơi mới ");

        lbNhatKy.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbNhatKy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNhatKy.setText(" Nhật Ký ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNhatKy, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTroChoiMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lbTroChoiMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lbNhatKy, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        lbX.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbX.setText(" X ");

        lbTrangChu.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbTrangChu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTrangChu.setText("#ChessChalenge");

        lbTroGiup.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbTroGiup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTroGiup.setText(" Trợ giúp ");

        lbGioiThieu.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbGioiThieu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbGioiThieu.setText(" Giới thiệu ");

        lbThoat.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbThoat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbThoat.setText(" Thoát ");

        lbIcon.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/chess.png"))); // NOI18N

        javax.swing.GroupLayout pnMenuLayout = new javax.swing.GroupLayout(pnMenu);
        pnMenu.setLayout(pnMenuLayout);
        pnMenuLayout.setHorizontalGroup(
            pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnMenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbX, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(pnMenuLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnMenuLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lbIcon))
                    .addComponent(lbGioiThieu, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTroGiup, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnMenuLayout.setVerticalGroup(
            pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMenuLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lbX)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbIcon)
                .addGap(18, 18, 18)
                .addComponent(lbTrangChu)
                .addGap(35, 35, 35)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(lbTroGiup, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(lbGioiThieu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(lbThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(pnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 0, 755));

        lbMenu.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Menu Bar icon.jpg"))); // NOI18N
        jPanel3.add(lbMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 26, 49, 36));

        txtNumber.setFont(new java.awt.Font("Arial", 1, 68)); // NOI18N
        txtNumber.setForeground(new java.awt.Color(153, 0, 0));
        txtNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumber.setText("8");
        jPanel3.add(txtNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(779, 338, 155, 79));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Kích thước bàn cờ mong muốn: ");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 354, 288, 39));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Trò chơi: ");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 490, 108, 39));

        rbtQueen.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup.add(rbtQueen);
        rbtQueen.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        rbtQueen.setSelected(true);
        rbtQueen.setText("N Quân Hậu ");
        jPanel3.add(rbtQueen, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 480, 147, 29));

        rbtKnight.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup.add(rbtKnight);
        rbtKnight.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        rbtKnight.setText("Mã Đi Tuần");
        jPanel3.add(rbtKnight, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 510, 147, 29));

        lbChoiNgay.setFont(new java.awt.Font("Times New Roman", 1, 42)); // NOI18N
        lbChoiNgay.setForeground(new java.awt.Color(153, 0, 0));
        lbChoiNgay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbChoiNgay.setText("Chơi ngay!");
        jPanel3.add(lbChoiNgay, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 450, 272, 98));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ỨNG DỤNG TRÒ CHƠI 8 QUÂN HẬU VÀ MÃ ĐI TUẦN");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 920, 94));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Game Assets - Game Background for Sidescroller Game.jpg"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 770));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1430, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TroChoiMoiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TroChoiMoiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TroChoiMoiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TroChoiMoiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TroChoiMoiView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbChoiNgay;
    private javax.swing.JLabel lbGioiThieu;
    private javax.swing.JLabel lbIcon;
    private javax.swing.JLabel lbMenu;
    private javax.swing.JLabel lbNhatKy;
    private javax.swing.JLabel lbThoat;
    private javax.swing.JLabel lbTrangChu;
    private javax.swing.JLabel lbTroChoiMoi;
    private javax.swing.JLabel lbTroGiup;
    private javax.swing.JLabel lbX;
    private javax.swing.JPanel pnMenu;
    private javax.swing.JRadioButton rbtKnight;
    private javax.swing.JRadioButton rbtQueen;
    private javax.swing.JTextField txtNumber;
    // End of variables declaration//GEN-END:variables
    
    public JLabel getLBMenu(){
        return lbMenu;
    }
    
    public JPanel getPNMenu(){
        return pnMenu;
    }
    
    public JLabel getPNClose(){
        return lbX;
    }
    
    public JLabel getLBTrangChu(){
        return lbTrangChu;
    }
    
    public JLabel getLBIcon(){
        return lbIcon;
    }
    
    public JLabel getLBTroChoiMoi(){
        return lbTroChoiMoi;
    }
        
    public JLabel getLBNhatKy(){
        return lbNhatKy;
    }
    
    public JLabel getLBTroGiup(){
        return lbTroGiup;
    }
        
    public JLabel getLBGioiThieu(){
        return lbGioiThieu;
    }
    
    public JLabel getLBThoat(){
        return lbThoat;
    }
    
    public JTextField getTXTNumber(){
        return txtNumber;
    }
    
    public ButtonGroup getButtonGroup(){
        return buttonGroup;
    }
    
    public JRadioButton getRBTQueen(){
        return rbtQueen;
    }
    
    public JRadioButton getRBTKnight(){
        return rbtKnight;
    }
    
    public JLabel getLBChoiNgay(){
        return lbChoiNgay;
    }

}
